# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: CrystalLang.Crystal
PackageVersion: 1.14.0
PackageLocale: en-US
Publisher: Cyrstal Lang Team
PublisherUrl: https://github.com/crystal-lang?type=source
PublisherSupportUrl: https://github.com/crystal-lang/crystal/issues
PackageName: Crystal
PackageUrl: https://crystal-lang.org
License: APACHE-2.0
LicenseUrl: https://github.com/crystal-lang/crystal/blob/master/LICENSE
ShortDescription: The Crystal Programming Language
Tags:
- compiler
- crystal
- crystal-language
- hacktoberfest
- programming-language
ReleaseNotesUrl: https://github.com/crystal-lang/crystal/releases/tag/1.14.0
PurchaseUrl: https://opencollective.com/crystal-lang
InstallationNotes: |-
  Please be aware of the fact that Crystal on Windows is not yet complete.
    See https://github.com/crystal-lang/crystal/issues/5430 for more information
Documentations:
- DocumentLabel: Reference Guide
  DocumentUrl: https://crystal-lang.org/reference
ManifestType: defaultLocale
ManifestVersion: 1.6.0
